[IV-23-24] Objetivo 0
johnwaves/recambios-express pull request #3
Opened 2023-09-18 15:04 UTC by johnwaves

* [ ] ¿Se trata de un problema real del que se tenga conocimiento personal?
* [ ] ¿Se trata de un problema que para solucionar requiera el despliegue
   de una aplicación en la nube?
* [ ] ¿La solución requiere una cierta cantidad de lógica de negocio, en vez
    solucionarse sólo almacenando y buscando?
* [ ] ¿Se ha incluído la configuración del repositorio y se ha enlazado desde el
`README`?
* [ ] ¿Tienes todos los datos necesarios para poder resolver el problema, o vas
a requerir que el usuario los introduzca?
* [ ] ¿Has seguido la lista de comprobación o estás marcando al buen tuntún
todo?

2023-09-18 18:56 UTC, johnwaves commented
@marcosrmartin

2023-09-18 19:02 UTC, johnwaves commented
@JJ

2023-09-19 05:50 UTC, JJ commented
> * [x]  ¿Se trata de un problema real del que se tenga conocimiento personal?
>       Sí. El problema se ha propuesto en base a experiencia y conocimiento personal, pues soy usuario frecuente de taxis y de servicios de _ride-sharing_ y comprendo la frustración por no prestar un servicio de calidad.

Quizás debería pararme aquí. "Ser usuario de" no equivale a tener conocimiento.

2023-09-19 05:53 UTC, JJ requested changes
Aparte de lo comentado, no parece un problema en el que tengas datos (consumo puntual de un automóvil, por ejemplo) o estaría ligado a un proceso físico (combustión del coche, o del motor que use).
Por último, no parece que aporte nada el que esté en la nube. Es una aplicación específica para un automóvil, que se podría ejecutar en el ordenador a bordo de ese automóvil.

2023-09-19 05:53 UTC, JJ commented on README.md
> +A continuación se muestran los aspectos clave que se deben abordar:
No estás describiendo un problema. Estás describiendo diferentes soluciones a un problema.

2023-09-20 11:50 UTC, johnwaves commented
> Aparte de lo comentado, no parece un problema en el que tengas datos (consumo puntual de un automóvil, por ejemplo) o estaría ligado a un proceso físico (combustión del coche, o del motor que use). Por último, no parece que aporte nada el que esté en la nube. Es una aplicación específica para un automóvil, que se podría ejecutar en el ordenador a bordo de ese automóvil.

He cambiado de idea teniendo en cuenta sus comentarios. ¿Debería editar la lista de comprobación del inicio del PR en base a lo que me ha surgido o la pongo en un nuevo comentario? Listo para revisión @JJ

2023-09-20 11:52 UTC, JJ commented
Claro, la lista de comprobación siempre tiene que reflejar el estado actual del PR.

2023-09-20 12:27 UTC, JJ requested changes
Adicionalmente, también de los errores frecuentes:

> Inventar problemas que no son reales desde el desconocimiento de las personas que tienen esa problemática. Una vez más, es imprescindible tener conocimiento real del problema para que se pueda intentar resolver.

En general, cuando se viaja se tiene muy claro qué es lo que se va a hacer y dónde, y se elige en función de dónde esté de oferta en Ryanair o de los colegas que quieran ir al mismo sitio. Incluso aunque admitamos que es un problema, obtener todos los datos para optimizar el viaje es un reto que es difícilmente superable.

2023-09-20 12:27 UTC, JJ commented on README.md
> +Cuando viajamos, ya sea por vacaciones, trabajo o simplemente porque queremos hacer una escapada y salir de la monotonía y el estrés diario, nos enfrentamos al problema de no saber qué hacer o visita
De los [errores frecuentes](https://github.com/JJ/IV-/blob/master/sesiones/errores-objetivo-0.md):

> Crear problemas demasiado vagos ("una persona quiere invertir") o simplemente descritos como tales ("el problema del transporte").

En este caso, "el problema de no saber qué hacer"

2023-09-20 12:47 UTC, johnwaves commented on README.md
> +Cuando viajamos, ya sea por vacaciones, trabajo o simplemente porque queremos hacer una escapada y salir de la monotonía y el estrés diario, nos enfrentamos al problema de no saber qué hacer o visita
Yo lo he pensado para los viajes, sobre todo, pues es más frecuente enfrentarse a esto aun teniéndolo todo organizado (o al menos planificado) si por algún casual sale un imprevisto. Pero pienso que la idea se puede ajustar también a cuando alguien es nuevo en una ciudad donde residirá durante un tiempo. ¿Debería entonces pensar en otra cosa? Tuve otras ideas pero me parecieron algo similares a las de unos compañeros, así que no sé qué hacer exactamente...

2023-09-20 12:51 UTC, JJ commented on README.md
> +Cuando viajamos, ya sea por vacaciones, trabajo o simplemente porque queremos hacer una escapada y salir de la monotonía y el estrés diario, nos enfrentamos al problema de no saber qué hacer o visita
Que trabajes con problemas propios es lo que se busca, pero debes mirar también a los aspectos que se han comentado.

2023-09-20 22:07 UTC, johnwaves commented on README.md
> +Cuando viajamos, ya sea por vacaciones, trabajo o simplemente porque queremos hacer una escapada y salir de la monotonía y el estrés diario, nos enfrentamos al problema de no saber qué hacer o visita
He encontrado un problema propio de mi vida estudiantil y que también se da en mi casa. He actualizado las respuestas de la lista de comprobación. Listo para revisión!

2023-09-21 05:28 UTC, JJ requested changes
Parece que nos vamos acercando, pero sigue siendo demasiado vago, hablando de "dificultades". Tampoco queda claro si se trata de algo relacionado con la compra, la búsqueda de una receta, o las dos cosas y cuál es exactamente el problema. Te animo a que profundices un poco más en este contexto para describir algún problema específico. Lo podemos hacer hoy en clase usando el juego de rol.

2023-09-21 11:55 UTC, johnwaves commented
> Parece que nos vamos acercando, pero sigue siendo demasiado vago, hablando de "dificultades". Tampoco queda claro si se trata de algo relacionado con la compra, la búsqueda de una receta, o las dos cosas y cuál es exactamente el problema. Te animo a que profundices un poco más en este contexto para describir algún problema específico. Lo podemos hacer hoy en clase usando el juego de rol.

Listo para revisión!

2023-09-21 11:55 UTC, JJ approved these changes
:+1: Voy a dejarlo pasar, pero asegúrate de que
1. Tienes datos para poder crear tests en el objetivo 4 que sean realistas. 
2. Tienes más o menos claro que hay una lógica de negocio no trivial para resolverlo y sabes cómo programarla.

Desde el desconocimiento, puede que este problema sea o súper simple o súper complejo. Si puedes añadir alguna aclaración más antes de fusionarlo, mejor. Si no, tendrás que irlo perfilando sobre todo cuando llegues al objetivo 2.

2023-09-21 11:58 UTC, johnwaves commented
> 👍 Voy a dejarlo pasar, pero asegúrate de que
> 
> 1. Tienes datos para poder crear tests en el objetivo 4 que sean realistas.
> 2. Tienes más o menos claro que hay una lógica de negocio no trivial para resolverlo y sabes cómo programarla.
> 
> Desde el desconocimiento, puede que este problema sea o súper simple o súper complejo. Si puedes añadir alguna aclaración más antes de fusionarlo, mejor. Si no, tendrás que irlo perfilando sobre todo cuando llegues al objetivo 2.

He aclarado un poco el problema en las respuestas a la lista de comprobación. ¿Debería añadirlo en el README?

2023-09-21 12:00 UTC, JJ commented
> > 👍 Voy a dejarlo pasar, pero asegúrate de que
> > 
> > 1. Tienes datos para poder crear tests en el objetivo 4 que sean realistas.
> > 2. Tienes más o menos claro que hay una lógica de negocio no trivial para resolverlo y sabes cómo programarla.
> > 
> > Desde el desconocimiento, puede que este problema sea o súper simple o súper complejo. Si puedes añadir alguna aclaración más antes de fusionarlo, mejor. Si no, tendrás que irlo perfilando sobre todo cuando llegues al objetivo 2.
> 
> He aclarado un poco el problema en las respuestas a la lista de comprobación. ¿Debería añadirlo en el README?

Claro, si no, ¿cómo quieres que quede en el repo?

2023-09-21 14:11 UTC, johnwaves commented
@JJ Sabiendo que no se pueden abrir dos PR para un mismo objetivo, ¿cómo hago para que se actualice el enlace de mi repositorio en el repo de la asignatura? Lo demás está todo modificado y listo.

2023-09-21 15:08 UTC, JJ commented
Solicítalo aquí

2023-09-22 11:13 UTC, merged