[IV-23-24] Objetivo 4: Tests
johnwaves/recambios-express pull request #47
Opened 2024-01-13 17:56 UTC by johnwaves

* [ ]  ¿Hay un camino claro que permita ir desde el código hasta la historia de
   usuario que desarrolla, pasando por el mensaje de commit y el issue
   correspondiente?
* [ ]  ¿Se ha intentado cubrir con tests una parte de la lógica de negocio que se
   esté desarrollando?
* [ ]  ¿Hay un producto mínimamente viable que describa lo que se va a entregar en
   este objetivo?
* [ ]  ¿En este producto mínimamente viable se han priorizado unas clases,
   módulos o paquetes más fundamentales frente a otros, movidos a otro
   PMV/Hito?
* [ ] ¿Estoy leyendo todo lo que marco o simplemente marco lo que se me pone por
delante?
* [ ] ¿Se han documentado las elecciones de biblioteca de aserciones y del
   de *test runner*?
* [ ] ¿Te has asegurado que lo que mencionas como biblioteca de aserciones y
test runners lo son realmente y tienen la misma funcionalidad? ¿O estás poniendo
`unittest` como *test runner* y `pytest` como biblioteca de aserciones?
* [ ] ¿Esa documentación incluye criterios de aceptación y también criterios de
búsqueda para las diferentes opciones?
* [ ]  ¿Se han seguido los principios F.I.R.S.T. en la creación del test y
   se ha documentado cómo se ha hecho?
* [ ]  ¿Se describe claramente en el PMV los tests que hay que pasar para que se
   considere viable?
* [ ] ¿Se han testeado también las excepciones?

2024-01-13 17:59 UTC, johnwaves commented
Cierro el issue #9 antes de seguir, pues ya quedó documentada la justificación de la elección del lenguaje de programación para el proyecto.

2024-01-26 13:31 UTC, carlotiii30 requested changes
Buenas! Creo que has trabajado bastante, sin embargo, hay un problema con los requisitos. Te he dejado un comentario que espero pueda ayudarte.

2024-01-26 13:31 UTC, carlotiii30 commented on docs/herramientas_test.md
> +Considerando estos criterios, se evalúan múltiples opciones.
Creo que más que criterios has definido requisitos.

2024-01-26 14:40 UTC, marinajcs requested changes
El PR tiene buena pinta en general, dejo aquí unas pequeñas sugerencias que espero que te ayuden a completar el objetivo 😃

2024-01-26 14:40 UTC, marinajcs commented on docs/herramientas_test.md
> +La elección de herramientas para las pruebas y los tests que se realizarán antes de entregar un PMV deben seguir la misma línea de los criterios establecidos para los gestores de dependencias y tarea
Ampliando lo mencionado por @carlotiii30, la compatibilidad con el lenguaje y toolchain actual quizás debería ser un requisito. 
Un ejemplo de criterio de selección podría ser el mantenimiento, importante para que las aserciones y frameworks no queden obsoletos. Estos aspectos puede evaluarse con buscadores como Snyk Advisor, que permite evaluar la calidad de las herramientas.

2024-01-26 16:06 UTC, johnwaves commented on docs/herramientas_test.md
> +Considerando estos criterios, se evalúan múltiples opciones.
Hola y gracias por la respuesta rápida.

Así es. Leyéndolo de nuevo parece que lo enfoqué más como requisitos y no definí como tal un criterio sólido. Lo voy a organizar de otra forma. Gracias de nuevo 😄.

2024-01-26 16:08 UTC, johnwaves commented on docs/herramientas_test.md
> +La elección de herramientas para las pruebas y los tests que se realizarán antes de entregar un PMV deben seguir la misma línea de los criterios establecidos para los gestores de dependencias y tarea
Hola y gracias por responder tan rápido.

Sí, efectivamente, y como le he comentado a @carlotiii30, lo he enfocado de otra forma. Gracias también por la mención del buscador. Voy a echarle un vistazo a todo y a reorganizar el documento de otra forma 😄.

2024-01-29 00:29 UTC, johnwaves commented
Lo he revisado y modificado. Gracias de nuevo por los comentarios, @carlotiii30 y @marinajcs! 😁

2024-01-29 07:27 UTC, carlotiii30 approved these changes
Muchas gracias por la reestructuración, lo veo mucho mejor.

2024-01-29 07:32 UTC, marinajcs approved these changes
No hay de qué, y gracias por considerar nuestro feedback, lo veo listo para revisión 😄

2024-01-29 08:17 UTC, johnwaves commented
@JJ listo para revisión.

2024-01-29 12:28 UTC, JJ requested changes
Ante todo, muchas gracias a @carlotiii30 y a @marinajcs por la revisión; convendría en todo caso que le dieras una pequeña vuelta. La lógica de negocio parece sólida (aunque la programación es posiblemente un poco compleja) pero hay una serie de temas que te agradecería que consideraras.

2024-01-29 12:28 UTC, JJ commented on docs/herramientas_test.md
> +Considerando estos criterios, se evalúan múltiples opciones.
Por favor, resolved todos los comentarios. En este caso, cambiando la línea se habría resuelto; si lo que has cambiado es algo en otro lugar, tienes que resolverlo explícitamente.

2024-01-29 12:28 UTC, JJ commented on docs/herramientas_test.md
> +- **Rendimiento de aserciones y pruebas**. Deben permitir la creación de aserciones rápidas, eficientes y flexibles.
Si no has testeado explícitamente, o consultado en algún artículo, el rendimiento, no puedes incluirlo. Incluid por favor sólo lo que hayáis considerado explícitamente a la hora de elegir. En tu elección de "Testify" no he visto que hayas mencionado en ningún momento su rendimiento.

2024-01-29 12:28 UTC, JJ commented on docs/herramientas_test.md
> +- **Generación de informes**. Otra cuestión de vital importancia es la capacidad que deben tener para generar informes o mostrar información relevante sobre los resultados de los tests.
Todos los tests runners tienen que generar informes, si no no son test runners.

2024-01-29 12:28 UTC, JJ commented on docs/herramientas_test.md
> +- **Facilidad de configuración**. Deben ser fáciles de configurar y utilizar.
"facilidad" no es algo que se pueda evaluar fácilmente. En todo caso, la mayoría de las bibliotecas no requieren más configuración que incluir la dependencia.

2024-01-29 12:28 UTC, JJ commented on docs/herramientas_test.md
> +- **Soporte para diversos tipos de pruebas**. Deben ser versátiles para soportar diferentes tipos de pruebas según sea necesario.
¿Qué tipos de pruebas necesitas? En todo caso, ¿ de qué nivel de biblioteca estás hablando? No son lo mismo las bibliotecas de aserciones que los test runners, ¿no?

2024-01-29 12:28 UTC, JJ commented on pkg/ruta.go
> +	if direccion.calle_numero == "" || direccion.poblacion == "" || direccion.codigo_postal == 0 {
¿No sería mejor que detectaras estos errores a nivel de `Pedido`? Si no te aseguras la corrección del objeto antes de pasarlo, estás cargando un montón de funciones adicionales con un montón de corrección de errores.

2024-01-29 12:28 UTC, JJ commented on pkg/ruta.go
> +		return errors.New("Los datos de la dirección postal están incompletos.")
Por otro lado, no te va a hacer falta hasta que llegues al objetivo 7, pero si el error no dice exactamente *cuál* es el dato que está incompleto, no es útil ni para depurar ni para el cliente.

2024-01-29 12:28 UTC, JJ commented on pkg/ruta.go
> +			return errors.New("Cada pieza debe tener una cantidad mayor a cero.")
Igual, no estás diciendo cuál pieza tiene ese problema y por otro lado no estás garantizando en la creación del objeto que sea correcto.

2024-01-29 12:28 UTC, JJ commented on pkg/ruta.go
> +		} else if pedido.Distancia < distanciaMaxima*0.75 {
No es buena práctica introducir literales en el código. Se deben definir constantes con un nombre significativo.

2024-01-29 12:28 UTC, JJ commented on pkg/ruta.go
> +		} else {
¿Es posible que `switch` sea un poco más sencillo de entender que estos if encadenados?

2024-01-29 14:59 UTC, johnwaves commented on pkg/ruta.go
> +		} else {
Sí, tal vez resulte menos complejo.

2024-01-31 09:39 UTC, JJ commented
Convendría que corrigieras esto a la mayor brevedad. Ánimo.

2024-02-01 06:40 UTC, johnwaves commented on docs/herramientas_test.md
> +- **Soporte para diversos tipos de pruebas**. Deben ser versátiles para soportar diferentes tipos de pruebas según sea necesario.
Con "tipos de pruebas" me refería a pruebas que no sean únicamente de comprobar si un campo está vacío.

Y no, no son lo mismo las bibliotecas de aserciones que los test runners. Voy a intentar modificarlo de tal forma que no se entienda así nuevamente, en caso de haber ocurrido.

2024-02-01 07:20 UTC, johnwaves commented
> Convendría que corrigieras esto a la mayor brevedad. Ánimo.

Listo de nuevo para revisión.

2024-02-01 07:50 UTC, JJ approved these changes
:+1:

2024-02-01 07:58 UTC, merged