[IV-23-24] Objetivo 5: Creación de un contenedor para pruebas
johnwaves/recambios-express pull request #54
Opened 2024-02-01 23:55 UTC by johnwaves

* [ ] ¿Se han establecido criterios previos de elección de la imagen base, así
como los criterios de búsqueda que han conducido a las imágenes que se están
considerando?
* [ ] ¿Se ha tenido en cuenta que la imagen es para testear, y que por tanto
tiene una función específica, tal como testear cómo va nuestra aplicación en la
última versión publicada del lenguage?
* [ ] ¿Se ha tenido en cuenta que la versión de la imagen base sea la última?
* [ ] ¿Se han tenido en cuenta criterios reales para la elección, y no criterios
irrelevantes como cuanto tiempo se tarda en construirla? (Se va a construir una
vez, se va a usar cientos o miles de veces)
* [ ] ¿Se han seguido las buenas prácticas en las órdenes que construyen
   la imagen? ¿Especialmente las relativas a usuarios no privilegiados y demás?
* [ ] ¿La imagen incluye sólo y exclusivamente la infraestructura
   necesaria para pasar los tests? Por ejemplo, si se ha elegido la imagen
   "oficial" (lo que hay que hacer sólo en casos muy justificados) ¿se ha
   comprobado que lo que se instale sea sólo y exclusivamente lo necesario para
   nuestro proyecto?
* [ ] ¿Se han documentado y enlazado los commits a las imágenes que se
   han testeado?
* [ ] ¿Está establecido correctamente como `WORKDIR` el que se va a usar en los
   tests que se van a lanzar?
* [ ] ¿Se usa algún directorio adecuado para copiar contenidos del repositorio
en vez del directorio de trabajo?
* [ ] ¿Se han establecido claramente los criterios de búsqueda y de aceptación de
   la imagen base?
* [ ] ¿Tienes claro cuales son las condiciones en las que tiene que actualizarse
la imagen en DockerHub y has configurado el workflow de acuerdo con ello? En
particular, ¿sabes qué condiciones tienen que darse para que se actualice y qué
condiciones *no* deben darse?
* [ ] Si se usan GitHub actions para su publicación, ¿se han considerado
cuidadosamene los criterios (ramas, paths) para que se lancen?
* [ ] ¿Se ha comprobado que el ENTRYPOINT del contenedor no escriba nada en el
directorio que monta, ya que no tiene derecho de escritura?
* [ ] ¿Se ha abierto un shell en el contenedor una vez construida la imagen y
comprobado que los ficheros que se necesitan están todos incluidos, y que no hay
ficheros que no se necesiten?

2024-02-11 18:35 UTC, JJ approved these changes
:+1:

2024-02-11 18:58 UTC, JJ requested changes
En un segundo vistazo, quizás deberías darle una pequeña vuelta. Y también me sentiría más cómodo si no usaras la imagen de bitnami elegida. Hay muchas otras imágenes que se pueden usar justificadamente.

2024-02-11 18:58 UTC, JJ commented on Dockerfile
> +RUN adduser --disabled-password -u 1001 test
¿Por qué deshabilitas la clave? ¿O le asignas el usuario 1001 a test? El que se use el usuario 1001 es sólo un ejemplo, diferentes sistemas de CI pueden tener diferentes UIDs.

2024-02-11 18:58 UTC, JJ commented on Dockerfile
> +ENV GOPROXY=https://proxy.golang.org,direct
¿Esto por qué lo haces?

2024-02-11 18:58 UTC, JJ commented on Dockerfile
> +ENV GOSUMDB=sum.golang.org
Como el resto del fichero, lo has [creado aquí](https://github.com/johnwaves/recambios-express/commit/52eed479dda882302ecc38fb3f9279dbacc72fe7) enlazando el issue #55, que no comenta qué problemas hay que resolver mediante esta variable de entorno.

2024-02-11 18:58 UTC, JJ commented on go.mod
> +	github.com/stretchr/objx v0.5.1 // indirect
Si no hay ningún módulo nuevo en este objetivo, ¿por qué se añade esto?

2024-02-11 18:58 UTC, JJ commented on Dockerfile
> +RUN go install github.com/go-task/task/v3/cmd/task@latest
¿Qué ventaja tiene instalarlo así frente a usar el binario?

2024-02-11 18:58 UTC, JJ commented on Dockerfile
> +COPY go.mod go.sum Taskfile.yml ./
¿Por qué necesitas el Taskfile aquí?

2024-02-11 19:16 UTC, JJ commented on Dockerfile
> +FROM bitnami/golang:latest
Entonces, según #56, cada vez que cambie la versión en latest tendrás que cambiar go.mod, ¿no?
*Eso* por definición es deuda técnica.

2024-02-12 23:43 UTC, johnwaves commented on Dockerfile
> +RUN adduser --disabled-password -u 1001 test
Deshabilité la clave porque tenía entendido que al crear usuarioos que fuesen temporales para pruebas o desarrollo no era necesario que tengan una contraseña.

2024-02-12 23:50 UTC, johnwaves commented on Dockerfile
> +RUN go install github.com/go-task/task/v3/cmd/task@latest
Tal vez por el hecho der ser más directo y sencillo.

2024-02-12 23:53 UTC, johnwaves commented on Dockerfile
> +COPY go.mod go.sum Taskfile.yml ./
Realmente no es necesario para esa orden, lo cambio.

2024-02-13 07:17 UTC, JJ commented on Dockerfile
> +RUN adduser --disabled-password -u 1001 test
¿En qué issue está eso incluido? Si le dejas la contraseña, ¿en qué cambiaría la operación de este imagen para ejecutar las pruebas?

2024-02-13 07:17 UTC, JJ commented on Dockerfile
> +RUN go install github.com/go-task/task/v3/cmd/task@latest
¿En qué sentido es esto más directo que descargarse el binario y colocarlo en un sitio donde se pueda ejecutar?

2024-02-13 07:29 UTC, JJ requested changes
Está bien que uses una construcción en dos fases, pero en ningún momento lo has justificado en la elección de las imágenes base. 
Aparte, ¿`go.sum` y `go.mod` tienen que quedarse en la imagen?
Aparte, ¿has mirado las vulnerabilidades que tiene la imagen que estás usando? ¿Tienen alguna importancia de por sí o en la aplicación en la que la estás usando?
Por otro lado, te agradecería que tuvieras esto listo antes del final de la mañana. La presentación tendría que ser mañana por la mañana (por la tarde no estoy disponible), así que convendría que lo supiéramos con cierto tiempo de antelación.

2024-02-13 07:29 UTC, JJ commented on Dockerfile
> +RUN adduser -u 1001 test
¿por qué usas el UID 1001?

2024-02-13 07:29 UTC, JJ commented on README.md
> +**Bitnami** es la imagen seleccionada para la ejecución de los tests unitarios sobre este proyecto. Tanto los criterios seguidos como las demás imágenes candidatas se detallan [aquí](https://github.c
Esta no es la imagen seleccionada, ¿no?

2024-02-13 07:29 UTC, JJ commented on go.mod
> +go 1.21.7
Sigo pensando que cambiar la versión por el contenedo no es una buena idea. [¿No hay imágenes con Golang 1.18?](https://hub.docker.com/_/golang/tags?page=1&name=1.18)

2024-02-13 07:29 UTC, JJ commented on docs/eleccion_images.md
> +### [Bitnami](https://hub.docker.com/r/bitnami/golang)
Estás mezclando imágenes que tienen solo el sistema operativo con imágenes con Go instalado. Y no estás mencionando, por ejemplo, la imagen "oficial" que es la que estás usando.

2024-02-13 15:30 UTC, johnwaves commented
> Está bien que uses una construcción en dos fases, pero en ningún momento lo has justificado en la elección de las imágenes base. Aparte, ¿`go.sum` y `go.mod` tienen que quedarse en la imagen? Aparte, ¿has mirado las vulnerabilidades que tiene la imagen que estás usando? ¿Tienen alguna importancia de por sí o en la aplicación en la que la estás usando? Por otro lado, te agradecería que tuvieras esto listo antes del final de la mañana. La presentación tendría que ser mañana por la mañana (por la tarde no estoy disponible), así que convendría que lo supiéramos con cierto tiempo de antelación.

Voy a corregirlo y añadir lo que me faltó por explicar de la imagen. No he podido verlo antes por el trabajo.

2024-02-13 15:51 UTC, johnwaves commented
> Está bien que uses una construcción en dos fases, pero en ningún momento lo has justificado en la elección de las imágenes base. Aparte, ¿`go.sum` y `go.mod` tienen que quedarse en la imagen? Aparte, ¿has mirado las vulnerabilidades que tiene la imagen que estás usando? ¿Tienen alguna importancia de por sí o en la aplicación en la que la estás usando? Por otro lado, te agradecería que tuvieras esto listo antes del final de la mañana. La presentación tendría que ser mañana por la mañana (por la tarde no estoy disponible), así que convendría que lo supiéramos con cierto tiempo de antelación.

Comprobándolo nuevamente, tal vez podría prescindir de incluir `go.mod` en la imagen dado que el `ENTRYPOINT` es `["task", "test"]` y Task ya maneja la descarga y gestión de las dependencias. Por otra parte, `go.sum` también podría no incluirse, aunque por seguridad he leído que resulta una buena práctica dejarlo.

2024-02-13 15:55 UTC, johnwaves commented on go.mod
> +go 1.21.7
Sí que las hay, pero el grado de [vulnerabilidad](https://hub.docker.com/layers/library/golang/1.18-bullseye/images/sha256-740324e52de766f230ad7113fac9028399d6e03af34883de625dc2230ef7927e?context=explore) que presentan es mayor en comparación con versiones más recientes,

2024-02-13 16:12 UTC, johnwaves commented on Dockerfile
> +RUN adduser -u 1001 test
Si le asigno el UID 1001 al usuario test, me aseguro que el contenedor se ejecuta con ese usuario y su entorno preconfigurado, con los permisos necesarios para utilizar una caché para almacenar los resultados de las pruebas. Si no lo hago así, cuando ejecuto ```docker run -u 1001 -t -v `pwd`:/app/test/ johnwaves1/recambios-express``` me muestra que el acceso está denegado.

2024-02-14 07:30 UTC, JJ commented on go.mod
> +go 1.21.7
No me hagas trampas en el solitario. Ninguna de esas vulnerabilidades se debe a la versión de go. Mira tú mismo las capas que introducen vulnerabilidades. Si estás construyendo en dos fases, ¿cuales de esas vulnerabilidades te afectan?

2024-02-14 07:34 UTC, JJ requested changes
Lo siento, pero de lo que se trata es de que se pueda ejecutar el test con un usuario cualquiera. Sustituye 1001 en la ejecución del contenedor por 1111. Si no funciona, es que no lo estás haciendo correctamente. Hacer el truco de crear un usuario con el mismo UID no cubre los objetivos, porque no has diagnosticado correctamente el problema, ni lo has solucionado. Tampoco deberías haber cerrado el comentario sin reaccionar.

2024-02-14 07:34 UTC, JJ commented on Dockerfile
> +RUN adduser -u 1001 test
Precisamente por eso es por lo que tienes que usar el UID por omisión. Si el acceso está denegado, es que no estás cubriendo el objetivo.

2024-02-14 16:34 UTC, johnwaves commented
> Lo siento, pero de lo que se trata es de que se pueda ejecutar el test con un usuario cualquiera. Sustituye 1001 en la ejecución del contenedor por 1111. Si no funciona, es que no lo estás haciendo correctamente. Hacer el truco de crear un usuario con el mismo UID no cubre los objetivos, porque no has diagnosticado correctamente el problema, ni lo has solucionado. Tampoco deberías haber cerrado el comentario sin reaccionar.

Solucionado. La ejecución se puede llevar a cabo usando cualquier UID.

2024-02-15 07:37 UTC, JJ requested changes
Evidentemente, has solucionado los problemas que habías encontrado, pero deberías intentar no incluir otros.

2024-02-15 07:37 UTC, JJ commented on Dockerfile
> +ENV GOPATH=/cache
¿Seguro que es una buena idea hacer esto? ¿Lo que instales de Go se va a instalar aquí en este directorio? ¿GOPATH no debería estar también en el path?

2024-02-15 07:37 UTC, JJ commented on Dockerfile
> +RUN adduser test
Habiendo un usuario, ¿cuál es la práctica habitual para colocar `GOPATH`?

2024-02-15 07:41 UTC, JJ commented
Y te rogaría que solucionaras esto esta misma mañana, antes de las 2 de la tarde. Ya estamos en plazo extra, porque hiciste la entrega el domingo (el último día era el miércoles pasado) y ya se ha pasado la fecha de evaluación, que era ayer.

2024-02-15 07:41 UTC, JJ commented
Aparte, como ves, no está funcionando el workflow para construir la imagen.

2024-02-15 09:26 UTC, johnwaves commented on Dockerfile
> +ENV GOPATH=/cache
Así es, GOPATH debería estar en el path. Y lo que se instale lo hará en /cache, por tanto, he de cambiarlo.

2024-02-15 09:28 UTC, johnwaves commented on Dockerfile
> +RUN adduser test
La práctica habitual es colocar el `GOPATH` en el directorio del usuario. Lo modifico y lo actualizo en breve.

2024-02-15 10:07 UTC, johnwaves commented
@JJ, la GitHub action ya pasa los checks. El problema ocurría al utilizar `TOKEN` en vez de `PASSWORD`. Listo para revision.

2024-02-15 11:13 UTC, JJ requested changes
Créeme que lo siento, pero tendrás que corregir alguna cosa todavía.

2024-02-15 11:13 UTC, JJ commented on Dockerfile
> +RUN adduser test
Vale que esto esté fuera de la línea modificada, pero debes resolver todos los comentarios. Y ahora perdona que me ponga mijicas, pero estás creando el usuario *después* del home (dos líneas más arriba).

2024-02-15 11:13 UTC, JJ commented on Dockerfile
> +RUN mkdir -p "$GOPATH" "$GOCACHE" && chmod -R 777 "$GOPATH" "$GOCACHE"
Si `GOPATH` tiene estos permisos, ¿cualquier persona que monte esto puede borrar sus contenidos o añadir otros? Es una buena práctica añadir sólo los permisos que sean estrictamente necesarios. También estás creando estos path antes de crear el usuario, así que el propietario seguirá siendo ROOT.

2024-02-15 12:39 UTC, johnwaves commented on Dockerfile
> +RUN mkdir -p "$GOPATH" "$GOCACHE" && chmod -R 777 "$GOPATH" "$GOCACHE"
He estado intentando arreglar esto desde que escribió el comentaro pero no doy pie con bola, no sé exactamente cómo configurarlo dentro del directorio home y que tenga los permisos adecuados.

2024-02-15 12:51 UTC, johnwaves commented
Creo que he podido resolverlo @JJ

2024-02-15 12:52 UTC, JJ approved these changes
:+1:

2024-02-15 12:58 UTC, merged